#!/usr/bin/env python3
"""
Inject season-1 CTF challenges into index.html.

Auto-discovers every challenge directory in the sibling gardens-ctf repo
(matching `s01cNN` or legacy `cNN`) that contains a challenge.txt, and
rewrites the block between `<!-- SEASON1:BEGIN -->` and `<!-- SEASON1:END -->`
in output/index.html. Idempotent: safe to re-run after regenerating
challenges or adding new ones (c09, c10, c11, ...).

Usage:
    python3 build_season1.py [--ctf /path/to/gardens-ctf] [--index /path/to/index.html]
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
DEFAULT_CTF = REPO_ROOT.parent / "gardens-ctf"
DEFAULT_INDEX = REPO_ROOT / "output" / "index.html"

# Hand-picked display names, keyed by challenge number. Any challenge
# directory found on disk without an entry here falls back to a generic
# "s01cNN - Garden NN" label — override by adding a row.
# The GARDENS list in index.html must use identical strings so the
# verification dropdown lines up 1:1 with season1 headers.
DISPLAY_NAMES = {
    1: "Just A Little Flag Garden",
    2: "Garden of Quiet Rows",
    3: "Garden of Whispers",
    4: "The Medicinal Garden",
    5: "Gridway Garden",
    6: "Garden of the Flame of Integrity",
    7: "Garden of Bones",
    8: "Lunar Garden",
}

# Matches either `s01c07` or legacy `c07` (any zero-padded number).
DIR_RE = re.compile(r"^(?:s01)?c(\d+)$")

BEGIN_MARK = "<!-- SEASON1:BEGIN -->"
END_MARK = "<!-- SEASON1:END -->"


def discover_challenges(ctf_root: Path) -> list[tuple[int, str, Path]]:
    """Return [(n, slug, challenge_txt_path), ...] sorted by n."""
    found: dict[int, tuple[str, Path]] = {}
    for child in ctf_root.iterdir():
        if not child.is_dir():
            continue
        m = DIR_RE.match(child.name)
        if not m:
            continue
        n = int(m.group(1))
        cpath = child / "challenge.txt"
        if not cpath.exists():
            print(f"[warn] {child.name} has no challenge.txt, skipping", file=sys.stderr)
            continue
        # If both `s01cNN` and legacy `cNN` exist, prefer the `s01`-prefixed one.
        if n in found and not child.name.startswith("s01"):
            continue
        found[n] = (child.name, cpath)
    return [(n, slug, path) for n, (slug, path) in sorted(found.items())]


def display_name(n: int) -> str:
    base = DISPLAY_NAMES.get(n, f"Garden {n:02d}")
    return f"s01c{n:02d} - {base}"


def read_challenge_body(path: Path) -> str:
    """Return challenge.txt with the outer <pre>...</pre> stripped.

    The file is embedded verbatim inside our own <pre> wrapper, so
    zero-width / tag characters that carry the payload survive intact.
    """
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"^\s*<pre>\r?\n?", "", text)
    text = re.sub(r"\r?\n?\s*</pre>\s*$", "", text)
    return text


def render_section(anchor: str, garden_name: str, body: str) -> str:
    # Escape only the three characters that would break the HTML structure.
    # We intentionally do NOT touch any other codepoint — the stego payloads
    # rely on invisible unicode surviving untouched.
    def esc(s: str) -> str:
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    return (
        f'  <article class="season1-challenge" id="{anchor}">\n'
        f'    <h2>{esc(garden_name)}</h2>\n'
        f'    <p class="slug">// {anchor}</p>\n'
        f"    <pre>{esc(body)}</pre>\n"
        f"  </article>"
    )


def build_block(ctf_root: Path) -> tuple[str, int]:
    sections = []
    challenges = discover_challenges(ctf_root)
    for n, _slug, cpath in challenges:
        anchor = f"s01c{n:02d}"
        body = read_challenge_body(cpath)
        sections.append(render_section(anchor, display_name(n), body))
    return "\n".join(sections), len(challenges)


def inject(html: str, block: str) -> str:
    pattern = re.compile(
        re.escape(BEGIN_MARK) + r".*?" + re.escape(END_MARK),
        re.DOTALL,
    )
    if not pattern.search(html):
        raise SystemExit(
            f"could not find {BEGIN_MARK} ... {END_MARK} markers in index.html"
        )
    replacement = (
        f"{BEGIN_MARK}\n"
        f"  <!-- generated by build_season1.py — do not edit by hand -->\n"
        f"{block}\n"
        f"  {END_MARK}"
    )
    return pattern.sub(lambda _m: replacement, html, count=1)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ctf", default=str(DEFAULT_CTF), help=f"path to gardens-ctf (default: {DEFAULT_CTF})")
    ap.add_argument("--index", default=str(DEFAULT_INDEX), help=f"path to index.html (default: {DEFAULT_INDEX})")
    args = ap.parse_args()

    ctf_root = Path(args.ctf)
    index_path = Path(args.index)

    html = index_path.read_text(encoding="utf-8")
    block, count = build_block(ctf_root)
    if count == 0:
        raise SystemExit(f"no challenges found under {ctf_root}")
    new_html = inject(html, block)
    index_path.write_text(new_html, encoding="utf-8")
    print(f"[ok] wrote {index_path}")
    print(f"     {count} challenges from {ctf_root}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
